[theme]
base="dark"
primaryColor="#9abddc"
backgroundColor="#9abbdc"
secondaryBackgroundColor="#d1e5f4"
textColor="#3c3e40"
font="Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap, sans serif"